<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZlcllbx\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZlcllbx/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerZlcllbx.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerZlcllbx\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerZlcllbx\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Zlcllbx',
    'container.build_id' => '85c4f5e1',
    'container.build_time' => 1548267804,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerZlcllbx');
