<?php

namespace AppBundle\Repository;

/**
 * AdminLogsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminLogsRepository extends \Doctrine\ORM\EntityRepository
{
}
