<?php

namespace AppBundle\Repository;

/**
 * Cards_OldRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Cards_OldRepository extends \Doctrine\ORM\EntityRepository
{
}
