<?php

namespace AppBundle\Repository;

/**
 * GatesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GatesRepository extends \Doctrine\ORM\EntityRepository
{
}
