<?php

namespace AppBundle\Repository;

/**
 * TemporaryCardsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TemporaryCardsRepository extends \Doctrine\ORM\EntityRepository
{
    public function filterOnlyOne()
    {
        $this->createQueryBuilder('t')
            ->select('t.cardId')
            ->orderBy('t.id', 'DESC')
            ->setMaxResults(1)
            ->getQuery()
            ->getResult();
    }
}
