<?php

namespace AppBundle\Repository;

/**
 * WorkersOldRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkersOldRepository extends \Doctrine\ORM\EntityRepository
{
}
