<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'app.logger' shared autowired service.

include_once $this->targetDirs[3].'\\src\\AppBundle\\Service\\Logger.php';

return $this->services['app.logger'] = new \AppBundle\Service\Logger(${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->load('getDoctrine_Orm_DefaultEntityManagerService.php')) && false ?: '_'});
